# Set schedule
name: whippet-application-tagger

on:
  schedule:
  - cron: 0 0-23 * * *

jobs:
  whippet-application-tagger:
    runs-on: ubuntu-latest

    steps:
      - name: setup
        uses: actions/checkout@v2

      - name: Authenticate with GitHub CLI
        shell: bash       
        run: |
          echo "${{ secrets.GOVPRESS_TOOLS_TOKEN }}" | gh auth login --with-token

      - name: Run tagger script
        run: |
          cd $GITHUB_WORKSPACE/main
          bin/whippet-application-tagger.sh
